# Generated by Django 5.2 on 2025-04-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dozimetr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='dozimetry/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dose_power_range', models.CharField(max_length=100)),
                ('dose_range', models.CharField(max_length=100)),
                ('energy_range', models.CharField(max_length=100)),
                ('error', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Radiometr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='radiometry/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alpha_range', models.CharField(max_length=100)),
                ('beta_range', models.CharField(max_length=100)),
                ('error', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
